### ISSUE TITLE
Camera offers nullpointer?

### ISSUE THREAD

**Issue by beniroquai** [youseetoo/FreeDcam#1]
I was sucessful in compiling the code. However, when launching the app, I get the following error:

```

05/16 13:24:22: Launching 'app' on HUAWEI CLT-L29.
App restart successful without requiring a re-install.
$ adb shell am start -n "troop.com.freedcam/freed.cam.ActivityFreeDcamMain" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 23454 on device 'huawei-clt_l29-WCR0218623003653'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
D/ActivityThread: Attach thread to application
I/ActivityThread: Init compatible state: true
I/HwPartIawareFactory: add android.common.HwPartIawareFactoryImpl to memory.
I/HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=troop.com.freedcam#10197#256
I/HwApiCacheMangerEx: need clear apicache,because volumes changed,oldCnt=0 newCnt=1
I/HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=troop.com.freedcam#10197#0
I/HwApiCacheMangerEx: need clear apicache,because volumes changed,oldCnt=1 newCnt=1
I/HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=troop.com.freedcam#10197#256
I/HwApiCacheMangerEx: need clear apicache,because volumes changed,oldCnt=1 newCnt=1
D/native: Found attached 0
D/native: Calling class is: java.lang.Class
E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@4d59d0c
D/native: Found attached 0
I/AwareBitmapCacher: init processName:troop.com.freedcam pid=23454 uid=10197
D/native: Calling class is: java.lang.Class
I/HwTypeface: updateFont: scale=0.95
D/SystemFonts: areFontsVariable: script=Latn
I/ActivityThread: finishPreloaded preloadStatus 0
I/RmeSchedManager: init Rme, version is: v1.0
I/RtgSchedEvent: current pid:23454 AppType:-1
I/RmeSchedManager: init Rme, version is: v1.0
I/OpenGLRenderer: RenderThread: progress name = [troop.com.freedcam], viewCornerType = 0
I/iGraphics: [0020080c] pn: troop.com.freedcam, p: 23454
I/iGraphics: [0030080c] no spt app: troop.com.freedcam
V/ActivityThread: callActivityOnCreate
I/DecorView[]: pkgName:troop.com.freedcam old windowMode:0 new windoMode:1, isFixedSize:false
D/ActivityAbstract: onCreate
D/SettingsManager: load Settings
W/System: A resource failed to call close. 
I/op.com.freedca: Waiting for a blocking GC ClassLinker
W/System: A resource failed to call close. 
D/SettingsManager: Lookup PreDefinedConfigFile
W/System: A resource failed to call close. 
D/XmlParserWriter: Found 139 Devices in Xml
W/System: A resource failed to call close. 
D/SettingsManager: Lookup PreDefinedConfigFile done
D/XmlParserWriter: /storage/emulated/0/Android/data/troop.com.freedcam/files/dngprofiles.xml exists:false
D/ActivityAbstract: onCreatePermissionGranted
D/ActivityAbstract: initOnCreate()
D/ActivityFreeDcamMain: onCreate: 
D/SecureCamera: onCreate
D/CameraApiManager: Create camera BackgroundHandler
D/BackgroundHandlerThread: startBackgroundThreadCameraApiManager
D/ActivityThread: add activity client record, r= ActivityRecord{39996cb token=android.os.BinderProxy@774109d {troop.com.freedcam/freed.cam.ActivityFreeDcamMain}} token= android.os.BinderProxy@774109d
D/SecureCamera: onResume
D/ActivityFreeDcamMain: onResumeTasks() 
D/FileListController: needStorageAccessFrameWork true
D/CameraApiManager: addEventListner ThemeSampleMainFragment
D/BaseEventHandler: set EventListner : ThemeSampleMainFragment
D/BaseEventHandler: set EventListner : ThemeSampleMainFragment
D/ThemeSampleMainFragment: onViewCreated
D/CameraApiManager: onResume camera null:true PreviewSurfaceRdy:false cameraIsOpen:false
D/CameraApiManager: changePreviewPostProcessing()
D/ThemeSampleMainFragment: changePreviewPostProcessing
D/CameraApiManager: BackgroundHandler is null: false features detected: false app version changed: true
D/CameraApiManager: load featuredetector
D/CameraApiManager: Start FeatureDetector
D/PreviewController: init preview off
D/CameraFeatureDetector: CameraFeatureRunner process
D/ThemeSampleMainFragment: onResume
D/OrientationManager: start
D/SensorManager: 0x7eb20ce410 addFd fd=102
D/MouseWheelSynthesizer: mMoveStepInDp: 64, mMoveStepInPixel: 192, mUpTimeDelayed: 100
D/ViewRootImpl: ViewRootImpl mIsInProductivePCDisplay: false
I/HwPartPowerOfficeFactory: add HwPartPowerOfficeFactoryImpl to memory.
I/DecorView[]: pkgName:troop.com.freedcam old windowMode:1 new windoMode:1, isFixedSize:false
D/InputEventReceiver: dispatchInputInterval 1000000
I/RmeSchedManager: init Rme, version is: v1.0
I/RtgSchedEvent: current pid:23454 AppType:-1
D/OrientationManager: stop
D/LocationManager: stop location
D/CameraApiManager: onPause
D/ActivityFreeDcamMain: onPause() 
D/SecureCamera: onPause
W/VideoCapabilities: Unrecognized profile/level 0/0 for video/mpeg2
W/VideoCapabilities: Unrecognized profile/level 0/2 for video/mpeg2
W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
I/VideoCapabilities: Unsupported profile 5 for video/mpeg2
I/chatty: uid=10197(troop.com.freedcam) CameraApiManage identical 2 lines
I/VideoCapabilities: Unsupported profile 5 for video/mpeg2
W/VideoCapabilities: Unrecognized profile/level 1/32 for video/mp4v-es
W/VideoCapabilities: Unrecognized profile/level 32768/2 for video/mp4v-es
W/VideoCapabilities: Unrecognized profile/level 32768/64 for video/mp4v-es
D/ActivityFreeDcamMain: onPauseTasks() 
D/OrientationManager: stop
D/HiTouch_PressGestureDetector: onAttached, package=troop.com.freedcam, windowType=1, mIsHiTouchRestricted=false
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/AutoFitTexturviewPreview: onSurfaceTextureAvailable
D/CameraApiManager: onPreviewAvailable
D/MediaCodecInfoParser: MediaCodecInfo Name:c2.android.aac.encoder hwaccel:
D/MediaCodecInfoParser: MediaCodecInfo Name:OMX.google.aac.encoder hwaccel:
D/MediaCodecInfoParser: MediaCodecInfo Name:c2.android.amrnb.encoder hwaccel:
D/MediaCodecInfoParser: MediaCodecInfo Name:OMX.google.amrnb.encoder hwaccel:
D/MediaCodecInfoParser: MediaCodecInfo Name:c2.android.amrwb.encoder hwaccel:
D/MediaCodecInfoParser: MediaCodecInfo Name:OMX.google.amrwb.encoder hwaccel:
D/MediaCodecInfoParser: MediaCodecInfo Name:c2.android.flac.encoder hwaccel:
D/MediaCodecInfoParser: MediaCodecInfo Name:OMX.google.flac.encoder hwaccel:
D/MediaCodecInfoParser: MediaCodecInfo Name:c2.android.opus.encoder hwaccel:
D/MediaCodecInfoParser: MediaCodecInfo Name:OMX.hisi.video.encoder.avc hwaccel:
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileBaseline lvl: AVCLevel1
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileBaseline lvl: AVCLevel1b
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileBaseline lvl: AVCLevel11
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileBaseline lvl: AVCLevel12
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileBaseline lvl: AVCLevel13
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileBaseline lvl: AVCLevel2
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileBaseline lvl: AVCLevel21
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileBaseline lvl: AVCLevel22
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileBaseline lvl: AVCLevel3
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileBaseline lvl: AVCLevel31
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileBaseline lvl: AVCLevel32
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileBaseline lvl: AVCLevel4
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileBaseline lvl: AVCLevel41
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileBaseline lvl: AVCLevel42
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileBaseline lvl: AVCLevel5
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileBaseline lvl: AVCLevel51
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileMain lvl: AVCLevel1
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileMain lvl: AVCLevel1b
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileMain lvl: AVCLevel11
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileMain lvl: AVCLevel12
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileMain lvl: AVCLevel13
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileMain lvl: AVCLevel2
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileMain lvl: AVCLevel21
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileMain lvl: AVCLevel22
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileMain lvl: AVCLevel3
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileMain lvl: AVCLevel31
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileMain lvl: AVCLevel32
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileMain lvl: AVCLevel4
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileMain lvl: AVCLevel41
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileMain lvl: AVCLevel42
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileMain lvl: AVCLevel5
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileMain lvl: AVCLevel51
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileHigh lvl: AVCLevel1
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileHigh lvl: AVCLevel1b
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileHigh lvl: AVCLevel11
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileHigh lvl: AVCLevel12
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileHigh lvl: AVCLevel13
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileHigh lvl: AVCLevel2
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileHigh lvl: AVCLevel21
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileHigh lvl: AVCLevel22
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileHigh lvl: AVCLevel3
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileHigh lvl: AVCLevel31
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileHigh lvl: AVCLevel32
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileHigh lvl: AVCLevel4
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileHigh lvl: AVCLevel41
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileHigh lvl: AVCLevel42
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileHigh lvl: AVCLevel5
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileHigh lvl: AVCLevel51
D/MediaCodecInfoParser: Color format:COLOR_FormatSurface
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420Flexible
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420SemiPlanar
D/MediaCodecInfoParser: Color format:2130706433
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420Planar
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV422Planar
D/MediaCodecInfoParser: Color format:COLOR_FormatYCrYCb
D/MediaCodecInfoParser: Color format:COLOR_FormatCbYCrY
D/MediaCodecInfoParser: Color format:COLOR_FormatCrYCbY
D/MediaCodecInfoParser: Color format:COLOR_Format32bitARGB8888
D/MediaCodecInfoParser: Color format:2130706447
D/MediaCodecInfoParser: Color format:COLOR_Format32bitBGRA8888
D/MediaCodecInfoParser: Color format:COLOR_FormatYCbYCr
D/MediaCodecInfoParser: MediaCodecInfo Name:OMX.hisi.video.encoder.hevc hwaccel:
D/MediaCodecInfoParser: Type: video/hevc profile: HEVCProfileMain lvl: HEVCMainTierLevel1
D/MediaCodecInfoParser: Type: video/hevc profile: HEVCProfileMain lvl: HEVCMainTierLevel2
D/MediaCodecInfoParser: Type: video/hevc profile: HEVCProfileMain lvl: HEVCMainTierLevel21
D/MediaCodecInfoParser: Type: video/hevc profile: HEVCProfileMain lvl: HEVCMainTierLevel3
D/MediaCodecInfoParser: Type: video/hevc profile: HEVCProfileMain lvl: HEVCMainTierLevel31
D/MediaCodecInfoParser: Type: video/hevc profile: HEVCProfileMain lvl: HEVCMainTierLevel4
D/MediaCodecInfoParser: Type: video/hevc profile: HEVCProfileMain lvl: HEVCMainTierLevel41
D/MediaCodecInfoParser: Type: video/hevc profile: HEVCProfileMain lvl: HEVCMainTierLevel5
D/MediaCodecInfoParser: Type: video/hevc profile: HEVCProfileMain lvl: HEVCMainTierLevel51
D/MediaCodecInfoParser: Type: video/hevc profile: HEVCProfileMain lvl: HEVCMainTierLevel52
D/MediaCodecInfoParser: Type: video/hevc profile: HEVCProfileMain lvl: HEVCMainTierLevel6
D/MediaCodecInfoParser: Type: video/hevc profile: HEVCProfileMain lvl: HEVCMainTierLevel61
D/MediaCodecInfoParser: Type: video/hevc profile: HEVCProfileMain lvl: HEVCMainTierLevel62
D/MediaCodecInfoParser: Color format:COLOR_FormatSurface
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420Flexible
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420SemiPlanar
D/MediaCodecInfoParser: Color format:2130706433
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420Planar
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV422Planar
D/MediaCodecInfoParser: Color format:COLOR_FormatYCrYCb
D/MediaCodecInfoParser: Color format:COLOR_FormatCbYCrY
D/MediaCodecInfoParser: Color format:COLOR_FormatCrYCbY
D/MediaCodecInfoParser: Color format:COLOR_Format32bitARGB8888
D/MediaCodecInfoParser: Color format:2130706447
D/MediaCodecInfoParser: Color format:COLOR_Format32bitBGRA8888
D/MediaCodecInfoParser: Color format:COLOR_FormatYCbYCr
D/MediaCodecInfoParser: MediaCodecInfo Name:c2.android.avc.encoder hwaccel:
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileBaseline lvl: AVCLevel5
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileConstrainedBaseline lvl: AVCLevel5
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileMain lvl: AVCLevel5
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420Flexible
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420Planar
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420SemiPlanar
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420PackedPlanar
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420PackedSemiPlanar
D/MediaCodecInfoParser: Color format:COLOR_FormatSurface
D/MediaCodecInfoParser: MediaCodecInfo Name:OMX.google.h264.encoder hwaccel:
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileBaseline lvl: AVCLevel5
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileConstrainedBaseline lvl: AVCLevel5
D/MediaCodecInfoParser: Type: video/avc profile: AVCProfileMain lvl: AVCLevel5
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420Flexible
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420Planar
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420SemiPlanar
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420PackedPlanar
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420PackedSemiPlanar
D/MediaCodecInfoParser: Color format:COLOR_FormatSurface
D/MediaCodecInfoParser: MediaCodecInfo Name:c2.android.h263.encoder hwaccel:
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420Flexible
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420Planar
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420SemiPlanar
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420PackedPlanar
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420PackedSemiPlanar
D/MediaCodecInfoParser: Color format:COLOR_FormatSurface
D/MediaCodecInfoParser: MediaCodecInfo Name:OMX.google.h263.encoder hwaccel:
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420Flexible
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420Planar
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420SemiPlanar
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420PackedPlanar
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420PackedSemiPlanar
D/MediaCodecInfoParser: Color format:COLOR_FormatSurface
D/MediaCodecInfoParser: MediaCodecInfo Name:c2.android.hevc.encoder hwaccel:
D/MediaCodecInfoParser: Type: video/hevc profile: HEVCProfileMain lvl: HEVCMainTierLevel52
D/MediaCodecInfoParser: Type: video/hevc profile: HEVCProfileMainStill lvl: HEVCMainTierLevel52
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420Flexible
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420Planar
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420SemiPlanar
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420PackedPlanar
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420PackedSemiPlanar
D/MediaCodecInfoParser: Color format:COLOR_FormatSurface
D/MediaCodecInfoParser: MediaCodecInfo Name:c2.android.mpeg4.encoder hwaccel:
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420Flexible
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420Planar
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420SemiPlanar
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420PackedPlanar
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420PackedSemiPlanar
D/MediaCodecInfoParser: Color format:COLOR_FormatSurface
D/MediaCodecInfoParser: MediaCodecInfo Name:OMX.google.mpeg4.encoder hwaccel:
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420Flexible
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420Planar
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420SemiPlanar
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420PackedPlanar
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420PackedSemiPlanar
D/MediaCodecInfoParser: Color format:COLOR_FormatSurface
D/MediaCodecInfoParser: MediaCodecInfo Name:c2.android.vp8.encoder hwaccel:
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420Flexible
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420Planar
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420SemiPlanar
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420PackedPlanar
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420PackedSemiPlanar
D/MediaCodecInfoParser: Color format:COLOR_FormatSurface
D/MediaCodecInfoParser: MediaCodecInfo Name:OMX.google.vp8.encoder hwaccel:
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420Flexible
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420Planar
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420SemiPlanar
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420PackedPlanar
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420PackedSemiPlanar
D/MediaCodecInfoParser: Color format:COLOR_FormatSurface
D/MediaCodecInfoParser: MediaCodecInfo Name:c2.android.vp9.encoder hwaccel:
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420Flexible
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420Planar
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420SemiPlanar
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420PackedPlanar
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420PackedSemiPlanar
D/MediaCodecInfoParser: Color format:COLOR_FormatSurface
D/MediaCodecInfoParser: MediaCodecInfo Name:OMX.google.vp9.encoder hwaccel:
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420Flexible
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420Planar
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420SemiPlanar
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420PackedPlanar
D/MediaCodecInfoParser: Color format:COLOR_FormatYUV420PackedSemiPlanar
D/MediaCodecInfoParser: Color format:COLOR_FormatSurface
I/CameraManagerGlobal: Connecting to camera service
W/Gralloc3: mapper 3.x is not supported
D/Camera2FeatureDetectorTask: CameraCharacteristicsQcom.is_logical_camera not supported
I/chatty: uid=10197(troop.com.freedcam) CameraApiManage identical 1 line
D/Camera2FeatureDetectorTask: CameraCharacteristicsQcom.is_logical_camera not supported
D/Camera2FeatureDetectorTask: CameraCharacteristicsQcom.is_logical_camera not supported
D/Camera2FeatureDetectorTask: CameraCharacteristicsQcom.is_logical_camera not supported
W/libEGL: EGLNativeWindowType 0x7f079a03d0 disconnect failed
D/ActivityThread: Won't deliver top position change in state=5
D/ViewRootImpl: ViewRootImpl mIsInProductivePCDisplay: false
I/DecorView[]: pkgName:troop.com.freedcam old windowMode:1 new windoMode:1, isFixedSize:false
I/HiTouch_HiTouchSensor: ORIENTATION_LANDSCAPE
D/PhoneWindow: updateStyledWidth: CoordinationModeUtils is not foldable.
D/SecureCamera: onResume
D/ActivityFreeDcamMain: onResumeTasks() 
D/CameraApiManager: onResume camera null:true PreviewSurfaceRdy:true cameraIsOpen:false
I/BlockMonitor: dispatchingThrewException In MainThread
D/AndroidRuntime: Shutting down VM
I/QarthLog: [PatchStore] createDisableExceptionQarthFile
I/QarthLog: [PatchStore] create disable file for troop.com.freedcam uid is 10197
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: troop.com.freedcam, PID: 23454
    java.lang.RuntimeException: Unable to resume activity {troop.com.freedcam/freed.cam.ActivityFreeDcamMain}: java.lang.NullPointerException: Attempt to invoke interface method 'boolean freed.cam.apis.basecamera.CameraWrapperInterface.isCameraOpen()' on a null object reference
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5078)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5121)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:190)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8668)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean freed.cam.apis.basecamera.CameraWrapperInterface.isCameraOpen()' on a null object reference
        at freed.cam.apis.CameraApiManager.onResume(CameraApiManager.java:93)
        at freed.cam.ui.themesample.ThemeSampleMainFragment.onResume(ThemeSampleMainFragment.java:129)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:3039)
        at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:607)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:306)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
        at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:3086)
        at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:273)
        at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:458)
        at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:447)
        at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:240)
        at android.app.Activity.performResume(Activity.java:8376)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5068)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5121) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:190) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:219) 
        at android.app.ActivityThread.main(ActivityThread.java:8668) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109) 
I/Process: Sending signal. PID: 23454 SIG: 9
```

Does this sound familiar @KillerInk ? ;-)

**Comment by beniroquai** [comment]
Do I need to delete some cache/previous settings?

**Comment by beniroquai** [comment]
deleting and reinstalling fixed it ;-)
